domain: "biomlw.github.io"       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com

title: "Bioinspired Machine Learning Workshop"
description: > # this means to ignore newlines until "baseurl:"
  Summer Workshop on Bioinspired Machine Learning Workshop
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://biomlw.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2024_style/logos/2024_bioml_logo.png"

social: 
  name: Facebook
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2024_pages']

plugins:
  - jekyll-sitemap 
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: "https://www.facebook.com"
  - title: twitter
    url: "https://twitter.com"
  - title: instagram
    url: "https://www.instagram.com/"

# Build settings
markdown: kramdown
permalink: pretty